# https://taskfile.dev

version: '3'
interval: 400ms

env:
  LOG_LEVEL: debug
  MINIO_SERVER_URL: localhost:9000
  MINIO_ACCESS_KEY: weedio7suu0chaewipohYohheiXaiwaevieng1ee
  MINIO_SECRET_KEY: aePhooThoc6Ohm3wuDoog5aeveev3Ahy3zaa0vie
  MINIO_BUCKET: prod

tasks:
  templ:  
    deps: 
      - kill
    env:
      TEMPL_EXPERIMENT: rawgo
    sources:
      - "**/*.templ"
    generates:
      - "**/*_templ.go"
    cmds:
      - templ generate 

  kill:
    method: none
    cmds:
      - echo "Killing all processes"
      - pkill -f ./site || true
  
  # npm:
  #   method: none
  #   cmds:
  #     - npm run build:css
      
  site:
    method: none
    desc: build the site
    deps:
      # - npm
      - templ
    sources:
      - "**/*.go"
      - "**/*.md"
      - "static/**/*"
    generates:
      - ./site
    cmds:
      - go mod tidy
      - go build -o site ./cmd/app

  
  default:
    method: none
    deps:
      - task: site
    cmds:
      - ./site